# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "00d3f91fa22e7c60dd5628eebbe60753"
name = "VIP-early-access"
handle = "vip-early-access"
application_url = "https://cove-fifty-celebration-assured.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_product_listings,write_customers,read_customers"

[auth]
redirect_urls = ["https://cove-fifty-celebration-assured.trycloudflare.com/auth/callback", "https://cove-fifty-celebration-assured.trycloudflare.com/auth/shopify/callback", "https://cove-fifty-celebration-assured.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
